"""empty message

Revision ID: 032630b7610f
Revises: 4b3687177923
Create Date: 2024-11-28 21:05:19.260985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032630b7610f'
down_revision = '4b3687177923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall', sa.Integer(), nullable=True),
    sa.Column('fertilizer', sa.Integer(), nullable=True),
    sa.Column('nitrogen', sa.Integer(), nullable=True),
    sa.Column('phosphorus', sa.Integer(), nullable=True),
    sa.Column('potassium', sa.Integer(), nullable=True),
    sa.Column('yield_', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingdata')
    # ### end Alembic commands ###
