"""empty message

Revision ID: 21ff7dcef886
Revises: 032630b7610f
Create Date: 2024-11-28 21:40:00.188655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ff7dcef886'
down_revision = '032630b7610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingdata', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
