"""empty message

Revision ID: fc75b8b02de2
Revises: 558d0c778016
Create Date: 2024-12-03 22:03:05.505836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc75b8b02de2'
down_revision = '558d0c778016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
